import Head from 'next/head';
import Image from 'next/image';

import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../utils/requests';

export default function Home({ movies }) {
  return (
    <div>
      <Head>
        <title>hulu</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />

        {/* Nav */}
        <Nav />

        {/* results */}
        <Results movies={movies} />
      </main>
    </div>
  );
}

// the context contains urls, when the user comes to a server it come with a url - we need that url to fetch the data
// context contains the detail of url
export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());
  return {
    props: {
      movies: request.results,
    },
  };
}
